version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - TZ=Asia/Ho_Chi_Minh
  
  server:
    build: ./server
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/attendance
      - JWT_SECRET=your_jwt_secret
      - NODE_ENV=development
      - PORT=5000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./server:/app
      - /app/node_modules
    restart: unless-stopped

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ./client:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  mongo_data: 